# Generated by Django 5.0 on 2023-12-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_icone_feature_alter_servico_icone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='icone',
            old_name='criados',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='criados',
            new_name='criado',
        ),
    ]
